fix(cmocka): Don't mix uint/int functions, causing -Wsign-conversion
GCC showed the following when activating wide warning
sets and -Werror:

    error: conversion to ‘uintmax_t’ {aka ‘const long unsigned int’} from ‘long int’ may change the sign of the result [-Werror=sign-conversion]

Add the warning to the PICKY_DEVELOPER=ON mode.
Fix similar errors in tests found by combining that mode
with UNIT_TESTS=ON.

Reviewed-by: Andreas Schneider <asn@cryptomilk.org>